---
blank_issues_enabled: false
contact_links:
  - name: Questions on Discussions
    url: https://github.com/hasansezertasan/hwid/discussions/
    about: Ask questions about your own code or scenarios on the Discussions tab.
